name: applite_image_picker
description: A Flutter package to easily pick images from device or network, designed for flexibility and ease of use.
version: 0.0.1
homepage: https://github.com/freddydrodev/applite_image_picker
repository: https://github.com/freddydrodev/applite_image_picker
issue_tracker: https://github.com/freddydrodev/applite_image_picker/issues
documentation: https://github.com/freddydrodev/applite_image_picker#readme

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_dialog: ^2.5.0
  cached_network_image: ^3.4.1
  hugeicons: ^1.1.1
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Maintainer and authors
author: Freddy Drodev <freddydrodev@gmail.com>
maintainer: Freddy Drodev <freddydrodev@gmail.com>
# License
license: MIT

# Topics for discoverability
topics:
  - image
  - picker
  - gallery
  - camera
  - applite
  - appliteui

flutter:
  # No assets or fonts by default, add here if needed

